# Script for nightly build of phenix

# no continuous integration builds or pull requests
trigger: none
pr: none

resources:
  pipelines:
  - pipeline: build_cache
    source: 'Update build cache'
  - pipeline: data_cache
    project: phenix
    source: 'Update modules'
    trigger: true
  - pipeline: cctbx_data_cache
    project: cctbx_project
    source: 'Update data cache'
  - pipeline: cctbx_build_cache
    project: cctbx_project
    source: 'Update build cache'

stages:
- stage: Build
  displayName: Build
  jobs:
    - template: ./ci-build.yml
      parameters:
        modules: modules
        builder: phenix
