# Common Parameters:
#   modules: <modules artifact name>
#   pipeline: <pipeline name>
#   win: windows template (build or test)
#   linux: linux template (build or test)
#   osx: osx template (build or test)

jobs:
  - template: ${{ parameters.win }}
    parameters:
      vmImage: windows-2019
      vs: 2019
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ${{ parameters.linux }}
    parameters:
      distribution: centos
      version: [7]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ${{ parameters.osx }}
    parameters:
      vmImage: [11]
      xcode_version: [12, 5, 1]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
