# Common Parameters:
#   modules: <modules artifact name>
#   pipeline: <pipeline name>
#   win: windows template (build or test)
#   linux: linux template (build or test)
#   osx: osx template (build or test)

jobs:
  - template: ${{ parameters.win }}
    parameters:
      vmImage: vs2017-win2016
      vs: vs2017
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ${{ parameters.linux }}
    parameters:
      distribution: centos
      version: [7]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ${{ parameters.osx }}
    parameters:
      vmImage: [10, 15]
      xcode_version: [11, 3, 1]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
