# Common Parameters:
#   modules: <modules artifact name>
#   pipeline: <pipeline name>

jobs:
  - template: ./conda-win.yml
    parameters:
      vmImage: vs2017-win2016
      vs: vs2015
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ./conda-linux.yml
    parameters:
      distribution: centos
      version: [6]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ./conda-osx.yml
    parameters:
      vmImage: [10, 14]
      xcode_version: [11, 3, 1]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
