# Script for building CCTBX
# linux image descriptions
# https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
#
# Template Parameters:
#   pipeline: pipeline name
#
# Parameters:
#   distribution: centos, ubuntu
#   version: [6, 10]
#   modules: <modules artifact name>
#   builder: <cctbx builder>

jobs:
- job: ${{ format('{0}_{1}', parameters.distribution, join('_', parameters.version) ) }}
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 360
  strategy:
    maxParallel: 2
    matrix:
      python2.7:
        CONDA: Linux
        OS: linux-64
        PYTHON_VERSION: py27
        MODULES: ${{ parameters.modules }}
      python3.6:
        CONDA: Linux
        OS: linux-64
        PYTHON_VERSION: py36
        MODULES: ${{ parameters.modules }}
      python3.7:
        CONDA: Linux
        OS: linux-64
        PYTHON_VERSION: py37
        MODULES: ${{ parameters.modules }}
      python3.8:
        CONDA: Linux
        OS: linux-64
        PYTHON_VERSION: py38
        MODULES: ${{ parameters.modules }}

  container:
    image: ${{ parameters.distribution }}:${{ join('.', parameters.version) }}
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

  variables:
    artifact_name: ${{ parameters.distribution }}_${{ join('.', parameters.version) }}_$(PYTHON_VERSION)
    day: Sunday

  steps:
  - script: /tmp/docker info
    displayName: Get Docker information

  - script: |
      day=`date +%A`
      echo $(day)
      echo "##vso[task.setVariable variable=day]$day"
    displayName: Get day of week

  - script: echo $(day)
    displayName: Check day of week

  # https://github.com/ApexAI/performance_test/blob/master/azure-pipelines.yml#L9-L17

  # centos setup
  - script: |
      set -x -e
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "sed -i 's/mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/CentOS-Base.repo"
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "sed -i 's/#baseurl=http:\/\/mirror/baseurl=http:\/\/vault/g' /etc/yum.repos.d/CentOS-Base.repo"
      cat /etc/yum.repos.d/CentOS-Base.repo
    displayName: Modify yum repositories for CentOS 6
    condition: eq('${{ parameters.version[0] }}', 6)

  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "yum install -y sudo"
    displayName: Set up sudo for CentOS
    condition: eq('${{ parameters.distribution }}', 'centos')

  - script: |
      set -x -e
      sudo yum groupinstall -y 'Development Tools'
      sudo yum install -y mesa-libGLU-devel mesa-libGL-devel openssh openssl tcsh
      locale -a
    displayName: Install dependencies for CentOS
    condition: eq('${{ parameters.distribution }}', 'centos')

  - script: |
      sudo yum install -y python-argparse
    displayName: Install argparse for CentOS 6
    condition: eq('${{ parameters.version[0] }}', 6)

  - script: |
      echo "##vso[task.setvariable variable=LC_ALL]en_US.utf8"
    displayName: Setup locale for CentOS
    condition: eq('${{ parameters.distribution }}', 'centos')

  - script: |
      echo "##vso[task.setvariable variable=LC_ALL]C.utf8"
    displayName: Setup locale for CentOS 8
    condition: eq('${{ parameters.version[0] }}', 8)

  # ubuntu setup
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo for Ubuntu
    condition: eq('${{ parameters.distribution }}', 'ubuntu')

  - script: |
      sudo apt-get install -y build-essential curl git libgl1-mesa-dev libglu1-mesa-dev locales subversion tcsh
      sudo locale-gen en_US.UTF-8
      sudo update-locale
    displayName: Install dependencies for Ubuntu
    condition: eq('${{ parameters.distribution }}', 'ubuntu')

  - script: |
      echo "##vso[task.setvariable variable=LC_ALL]en_US.utf8"
    displayName: Setup locale for Ubuntu
    condition: eq('${{ parameters.distribution }}', 'ubuntu')

  - script: |
      echo $(System.CollectionId)
      echo $(System.CollectionUri)
      echo $(System.TeamProject)
      echo $(System.TeamProjectId)
      echo $(System.DefinitionID)
    displayName: Show System variables

  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific'
      project: '$(resources.pipeline.ci.projectID)'
      pipeline: '$(resources.pipeline.ci.pipelineID)'
      allowPartiallySucceededBuilds: true
      allowFailedBuilds: true
      artifact: '$(artifact_name)'
      path: $(Pipeline.Workspace)
    displayName: Download cached build

  - script: |
      cd $(Pipeline.Workspace)
      tar -xf build.tar
      rm build.tar
    displayName: Extract build tarball
    continueOnError: true
    failOnStderr: false

  # build
  - template: ./unix-conda-test.yml
    parameters:
      distribution: ${{ parameters.distribution }}
      version: ${{ parameters.version }}
      builder: ${{ parameters.builder }}
