# Script for downloading conda packages
# This lowers the chances of network failures by consolidating downloads.
# Also, wget will automatically retry downloads.
#
# Variables:
#   OS: linux-64, osx-64, win-64
#   PYTHON_VERSION: py27, py36, py37, py38

jobs:
- job: conda_packages
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 90
  strategy:
    maxParallel: 2
    matrix:
      linux_py37:
        OS: linux-64
        PYTHON_VERSION: py37
      linux_py38:
        OS: linux-64
        PYTHON_VERSION: py38
      linux_py39:
        OS: linux-64
        PYTHON_VERSION: py39
      macos_py37:
        OS: osx-64
        PYTHON_VERSION: py37
      macos_py38:
        OS: osx-64
        PYTHON_VERSION: py38
      macos_py39:
        OS: osx-64
        PYTHON_VERSION: py39
      win_py37:
        OS: win-64
        PYTHON_VERSION: py37
      win_py38:
        OS: win-64
        PYTHON_VERSION: py38
      win_py39:
        OS: win-64
        PYTHON_VERSION: py39

  steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: cci.lbl.gov,131.243.194.153 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAnPOtqyYASs6hc3fsmUQn92ovSozJsMsJyrMWjppUERX1tD4Fh0D7YaNhLvYpKi5mYVREo+tsKoOatCcqKGHCONWpzx7JHXUzfIBsy6nCeygRyyW4yuyoCuYFvOYLkaM4PrN/7XaZEnp1ux6/ZcbRxBDNK4f42svJUV39OX33tRuQWpP+O85paJr1ePHVz6U2n14a+3fRN3DBMti1dJuKOThU4djYEBQimx54pnW71eYORN2oUz+N/4RHAcomtxZpcUMl3Qadw8hD4s1XM6fzJ0Que7KefnnrPOgAEtZxKl9j09aaE70Oh+ie5Y6ckwddJ/4qZB5m2tBaEi3xuy0TSQ==
      sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA7XgVgdU9GmZuo5yVyW/htrAuxe7ypuq7IowWwfUC0WZw9SPzQ8kOGj63plF3ytx/qpgvUlS1AiywO20rZ83gHmRdAiuvt9laH09KlWEUhIhAQTzesqBG5aUT0MKo01yxijoRl5HC8w/MdOanc0h01e6IxnZvgG0N30RB1i4xVPCtR/VBmXSp4R0T+Q/gJjfQssuBxHVMrrute4V3uUHek58FL2QgUB0+zq6ipETjuCJxTSyYVAFtCYDPYs+0lAYYkWrXALCr9kX9s22jYtkyv5kNw6mEW8nhtA7GbTdJLv4M6/WYtcvQV8TDcNCfltOfl81U3gcZ9zhQDKGVoNaJEw== buildbot@cci.lbl.gov
      sshKeySecureFile: id_rsa
    displayName: Download SSH key

  - checkout: phenix
    path: ./modules/phenix

  - script: |
      cd $(Pipeline.Workspace)
      mkdir $(PYTHON_VERSION)_$(OS)
      cd $(PYTHON_VERSION)_$(OS)
      for url in `grep https $(Pipeline.Workspace)/modules/phenix/conda_envs/phenix_$(PYTHON_VERSION)_$(OS).txt`; do
        filename=${url##*/}
        filename=${filename%#*}
        directory=`echo ${url} | cut -f5 -d"/"`
        if [ "${directory}" = "main" ]; then
          directory=`echo ${url} | cut -f6 -d"/"`
        fi
        mkdir -p ${directory}
        cd ${directory}
        echo Downloading ${filename} to ${directory}
        wget --retry-connrefused --retry-on-http-error=520 ${url}
        cd ..
        if [ "$(OS)" = "win-64" ]; then
          echo ${directory}\\${filename} >> filenames.txt
        else
          echo ${directory}/${filename} >> filenames.txt
        fi
      done
      ls
    displayName: Download conda packages

  - publish: $(Pipeline.Workspace)/$(PYTHON_VERSION)_$(OS)
    artifact: $(PYTHON_VERSION)_$(OS)
