# Common Parameters:
#   modules: <modules artifact name>
#   pipeline: <pipeline name>

jobs:
  - template: ./conda-win.yml
    parameters:
      vmImage: vs2017-win2016
      vs: vs2015
      modules: ${{ parameters.modules }}
      pipeline: ${{ parameters.pipeline }}
      builder: ${{ parameters.builder }}
      test_module: ${{ parameters.test_module }}
  # - template: ./conda-win.yml
  #   parameters:
  #     vmImage: vs2017-win2016
  #     vs: vs2017
  #     modules: ${{ parameters.modules }}
  #     pipeline: ${{ parameters.pipeline }}
  #     builder: ${{ parameters.builder }}
  #     test_module: ${{ parameters.test_module }}
  - template: ./conda-linux.yml
    parameters:
      distribution: centos
      version: [6]
      modules: ${{ parameters.modules }}
      pipeline: ${{ parameters.pipeline }}
      builder: ${{ parameters.builder }}
      test_module: ${{ parameters.test_module }}
  # - template: ./conda-linux.yml
  #   parameters:
  #     distribution: centos
  #     version: [7]
  #     modules: ${{ parameters.modules }}
  #     pipeline: ${{ parameters.pipeline }}
  #     builder: ${{ parameters.builder }}
  #     test_module: ${{ parameters.test_module }}
  # - template: ./conda-linux.yml
  #   parameters:
  #     distribution: centos
  #     version: [8]
  #     modules: ${{ parameters.modules }}
  #     pipeline: ${{ parameters.pipeline }}
  #     builder: ${{ parameters.builder }}
  #     test_module: ${{ parameters.test_module }}
  # - template: ./conda-linux.yml
  #   parameters:
  #     distribution: ubuntu
  #     version: ['18', '04']
  #     modules: ${{ parameters.modules }}
  #     pipeline: ${{ parameters.pipeline }}
  #     builder: ${{ parameters.builder }}
  #     test_module: ${{ parameters.test_module }}
  # - template: ./conda-linux.yml
  #   parameters:
  #     distribution: ubuntu
  #     version: ['16', '04']
  #     modules: ${{ parameters.modules }}
  #     pipeline: ${{ parameters.pipeline }}
  #     builder: ${{ parameters.builder }}
  #     test_module: ${{ parameters.test_module }}
  # - template: ./conda-linux.yml
  #   parameters:
  #     distribution: ubuntu
  #     version: ['20', '04']
  #     modules: ${{ parameters.modules }}
  #     pipeline: ${{ parameters.pipeline }}
  #     builder: ${{ parameters.builder }}
  #     test_module: ${{ parameters.test_module }}
  # - template: ./conda-osx.yml
  #   parameters:
  #     vmImage: [10, 15]
  #     xcode_version: [11, 5]
  #     modules: ${{ parameters.modules }}
  #     pipeline: ${{ parameters.pipeline }}
  #     builder: ${{ parameters.builder }}
  #     test_module: ${{ parameters.test_module }}
  - template: ./conda-osx.yml
    parameters:
      vmImage: [10, 14]
      xcode_version: [11, 3, 1]
      modules: ${{ parameters.modules }}
      pipeline: ${{ parameters.pipeline }}
      builder: ${{ parameters.builder }}
      test_module: ${{ parameters.test_module }}
  # - template: ./conda-osx.yml
  #   parameters:
  #     vmImage: [10, 14]
  #     xcode_version: [10, 3]
  #     modules: ${{ parameters.modules }}
  #     pipeline: ${{ parameters.pipeline }}
  #     builder: ${{ parameters.builder }}
  #     test_module: ${{ parameters.test_module }}
