# Common Parameters:
#   modules: <modules artifact name>
#   pipeline: <pipeline name>

jobs:
  - template: ./conda-win.yml
    parameters:
      vmImage: windows-2019
      vs: vs2019
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  # - template: ./conda-linux.yml
  #   parameters:
  #     distribution: centos
  #     version: [6]
  #     modules: ${{ parameters.modules }}
  #     builder: ${{ parameters.builder }}
  - template: ./conda-linux.yml
    parameters:
      distribution: centos
      version: [7]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ./conda-linux.yml
    parameters:
      distribution: rockylinux
      version: [8]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ./conda-linux.yml
    parameters:
      distribution: ubuntu
      version: ['18', '04']
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ./conda-linux.yml
    parameters:
      distribution: ubuntu
      version: ['16', '04']
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ./conda-linux.yml
    parameters:
      distribution: ubuntu
      version: ['20', '04']
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ./conda-osx.yml
    parameters:
      vmImage: [10, 15]
      xcode_version: [12, 4]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ./conda-osx.yml
    parameters:
      vmImage: [10, 15]
      xcode_version: [11, 3, 1]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
  - template: ./conda-osx.yml
    parameters:
      vmImage: [11]
      xcode_version: [13, 2, 1]
      modules: ${{ parameters.modules }}
      builder: ${{ parameters.builder }}
