# Script for checking out sources and storing it as an artifact
# The artifact name is "modules"
#
# Parameters:
#   flags: <empty>, --use-conda
#   optimization: <empty>, 0, 1, 2, 3

jobs:
- job: modules${{ parameters.optimization }}
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 120

  steps:

  - task: DownloadSecureFile@1
    name: ssh_config
    inputs:
      secureFile: ssh.config

  # download sources
  - checkout: cctbx_project
    path: ./modules/cctbx_project

  - script: |
      set -xe
      cd $(Pipeline.Workspace)
      ln -s modules/cctbx_project/libtbx/auto_build/bootstrap.py
    displayName: Link bootstrap.py

  - script: |
      set -xe
      cd $(Pipeline.Workspace)
      export SVN_SSH="ssh -F $(ssh_config.secureFilePath)"
      python bootstrap.py hot update --builder=voyager --python=39 ${{ parameters.flags }}
    displayName: Download sources

  # select Boost version
  - script: |
      set -xe
      cd cd $(Pipeline.Workspace)/modules/boost
      git checkout 1.74
    displayName: Select Boost 1.74

  # change optimization level (linux, macOS)
  - script: |
      set -xe
      cd $(Pipeline.Workspace)/modules/cctbx_project/libtbx
      # Remove -ffast-math
      sed -i 's/-ffast-math//g' SConscript
      # Change -O level
      sed -i 's/-O3/-O${{ parameters.optimization }}/g' SConscript
    displayName: Changing optimization (linux, macOS)
    condition: or(eq('${{ parameters.optimization }}', 0), eq('${{ parameters.optimization }}', 1), eq('${{ parameters.optimization }}', 2), eq('${{ parameters.optimization }}', 3))

  # change optimization level (Windows)
  - script: |
      set -xe
      cd $(Pipeline.Workspace)/modules/cctbx_project/libtbx
      # Remove /fp:fast
      sed -i 's/\/fp:fast//g' SConscript
      # Change /O2 to /O1
      sed -i 's/\/O2/\/O1/g' SConscript
    displayName: Changing optimization (Windows)
    condition: or(eq('${{ parameters.optimization }}', 0), eq('${{ parameters.optimization }}', 1))

  # preserve permissions
  - script: |
      set -xe
      cd $(Pipeline.Workspace)
      tar -chf modules.tar modules
    displayName: Build tarball

  # publish artifact
  - publish: $(Pipeline.Workspace)/modules.tar
    artifact: modules${{ parameters.optimization }}
    continueOnError: true
